const CONFIG = {};

CONFIG.SERVER_URL = 'http://localhost:3000';

CONFIG.HOME_MENU_ITEM_KEY = '10';
CONFIG.SALES_ORDERS_MENU_ITEM_KEY = '20';
CONFIG.PURCHASE_ORDERS_MENU_ITEM_KEY = '30';
CONFIG.DATA_SUB_MENU_KEY = '40SM';
CONFIG.INVENTORY_MENU_ITEM_KEY = '41';
CONFIG.SUPPLIER_MENU_ITEM_KEY = '42';

export default CONFIG;
