import React, { useState } from 'react';
import { Link, Route, Switch } from 'react-router-dom';
import {
  HomeOutlined,
  DollarOutlined,
  BarChartOutlined,
  ShoppingCartOutlined,
  SettingOutlined,
  LogoutOutlined,
  BellOutlined,
  ExclamationCircleOutlined
} from '@ant-design/icons';
import { Layout, Menu, Row, Col, Tooltip, Modal } from 'antd';

import BilboSidebar from './BilboSidebar';
import BilboHeader from './BilboHeader';

import HomePage from '../HomePage';
import SalesPage from '../SalesPage';
import PurchasePage from '../PurchasePage';
import SettingsPage from '../SettingsPage';
import ErrorPage from '../ErrorPage';

import CONFIG from '../../config';
import { NavigationContext } from '../../context/NavigationContext';

const { Header, Content, Sider } = Layout;
const { SubMenu } = Menu;

import styled from 'styled-components';

// const IconDiv = styled.div`
//   color: ${props => props.theme.colors.salmon};
//   background: ${props => props.theme.colors.darkerRed};
//   width: ${props => props.theme.settings.layoutHeaderHeight};
//   height: ${props => props.theme.settings.layoutHeaderHeight};
//   font-size: ${props => props.theme.settings.headerIconFontSize};
//   text-align: center;

//   &:hover {
//     ${'' /* background: ${props => props.theme.colors.darkerRed}; */}
//     color: ${props => props.theme.colors.white};
//   }
// `;

// function HeaderIconButton(props) {
//   return (
//     <Tooltip placement='bottom' title={props.tooltipTitle}>
//       <IconDiv onClick={props.onClick}>
//         {props.iconComponent}
//       </IconDiv>
//     </Tooltip>
//   );
// }

// const BilboHeader = styled(Header)`
//   padding-right: 0px;
// `;

// const { confirm } = Modal;
// function showLogoutConfirmationModal() {
//   confirm({
//     icon: <ExclamationCircleOutlined />,
//     content: 'Are you sure you wish to log out?',
//     onOk: () => {
//       alert('clicked ok');
//     }, 
//     onCancel: () => {
//       alert('clicked cancel');
//     }
//   })
// }

// TODO: Refactor into BilboSider, BilboHeader, BilboContent?
/**
 * Scaffold Component that serves as the point of
 * entry for any authenticated user. The routes 
 * contained within the scaffold determine which
 * pages are being displayed in the content part
 * of the screen. The scaffold also defines the 
 * UI common to all pages in the app (i.e. sidebar,
 * header etc.)
 */
export default class AppScaffold extends React.Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <Layout style={{ minHeight: '100vh' }}>

        <BilboSidebar />
        <Layout>
          <BilboHeader />
          <Content style={{ margin: '10px 10px', background: 'green', height:'100px', overflowY:'scroll' }}>
            <Switch>
              <Route exact path={CONFIG.HOME_URL} component={HomePage} />
              <Route path={CONFIG.SALES_ORDERS_URL} component={SalesPage} />
              <Route path={CONFIG.PURCHASE_ORDERS_URL} component={PurchasePage} />
              <Route path={CONFIG.SETTINGS_URL} component={SettingsPage} />
              <Route path='*' component={ErrorPage} />
            </Switch>

                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />
                ...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />...
                <br />

                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>

                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>
                <h1>hello again</h1>

                <h1>hello again</h1>

                <h1>hello again</h1>
          </Content>
        </Layout>
      </Layout>
    );
  }
}
